Add blog post for Replo Case Study
snowpackdata/website pull request #41
Opened 2024-06-10 22:34 UTC by dpblume

2024-06-10 22:42 UTC, dpblume commented on blog/html_files/case-study-replo.html
> + <br>We implemented Dagster, an open-source orchestration tool that enables users to build, schedule, and execute data pipelines. Dagster allows Replo to schedule and execute dbt jobs, monitor the fr
Note: need to update this to the followup blog post link

2024-06-10 22:47 UTC, nathanaelrobinson approved these changes
Looks good! I like the Fuji cityscape splash too

2024-06-10 22:47 UTC, nathanaelrobinson commented on blog/posts/case-study-replo-data-stack.json
> +  "tags" : ["case-study", "data-stack", "etl", "consulting", "dbt", "snowflake", "airbyte", "dagster"],
Nice, anything with the "case-study" tag will also show up on our case studies URL fyi so this is perfect.

2024-06-10 22:47 UTC, nathanaelrobinson commented on blog/html_files/case-study-replo.html
> + <br>We implemented Dagster, an open-source orchestration tool that enables users to build, schedule, and execute data pipelines. Dagster allows Replo to schedule and execute dbt jobs, monitor the fr
Wanna just pull the link out entirely for now so we don't link people to a random Google Doc? 

```suggestion
 <br>We implemented Dagster, an open-source orchestration tool that enables users to build, schedule, and execute data pipelines. Dagster allows Replo to schedule and execute dbt jobs, monitor the freshness of tables and their upstream sources, and provides an intuitive UI for interacting with the dbt project. We wrote more in-depth on why Dagster and dbt complement each other so well in a follow-up blog post, where you can see the end result of this project in action. We self-hosted and deployed the Dagster project to AWS to ensure that it can handle increasing data volume and complexity, while keeping costs relatively stable month-to-month as Replo continues to grow (i.e. they are not tied to variable per-user pricing). Marrying Dagster with their dbt project provided an interactive UI and self-service capabilities for both expert and non-technical users to manage their analytics pipelines.</p>
```

2024-06-10 23:30 UTC, nathanaelrobinson approved these changes
Merge away!

2024-06-10 23:32 UTC, nathanaelrobinson requested changes
Can you limit the size of the image -- it's currently overlflowing out of my screen.

2024-06-10 23:36 UTC, nathanaelrobinson requested changes
Two more quick things:

If you run it locally you'll see your bullet point numbers are too small to read -- you might need to edit the style on the `<ol>` tag.

Also total nit but can you add a `<hr>` tag before the last paragraph so its below the fold.

<img width="1102" alt="Screenshot 2024-06-10 at 4 34 34 PM" src="https://github.com/snowpackdata/website/assets/20802132/e2c776ce-eda4-4d9b-9b7b-b4edf33a2342">


this one pictured? The `<hr>` tag will add a thin line across the page so that it separates the blog content from the "salesy" stuff

2024-06-11 04:03 UTC, dpblume commented
Thanks for catching these. I think these should all be fixed:

<img width="1119" alt="image" src="https://github.com/snowpackdata/website/assets/156969636/ab61d4ff-8bed-4d4c-89d4-eab14b34f549">

2024-06-11 04:03 UTC, nathanaelrobinson approved these changes
Looks good! Feel free to merge! When you check the "actions" tab you'll see when the deploy has been merged and it's available live.

2024-06-11 04:04 UTC, merged